- name: catalogue
  hosts: catalogue
  become: yes
  tasks: 
    - name: Disable old Nodejs and enable Nodejs:18
      ansible.builtin.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y ;

    - name: install nodejs
      ansible.builtin.package:
      name: nodejs
      state: present

      