- name: Installing MySQL componenets
  hosts: mysql 
  become: yes 
  tasks:
    - name: disbling mysql
      ansible.builtin.shell: dnf module disable mysql -y

    - name: copy mysql.repo
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: Install mysql
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    - name: Enable and Start MySQL
      ansible.builtin.service:
        name: mysqld
        enabled: yes 
        state: started

    - name: setup root password
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
