- name: Installing Payment componenets
  hosts: payment 
  become: yes 
  tasks: 
    - name: Installing python GCC 3.6
      ansible.builtin.command: dnf install python36 gcc python3-devel -y

    - name: Add roboshop 
      ansible.builtin.user:
        name: roboshop

    - name: Recursively remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download catalogue.zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/payment.zip
        dest: /tmp 

    - name: Unzip payment.zip
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app 
        remote_src: yes 

    - name: Install dependencies
      ansible.builtin.command: pip3.6 install -r requirements.txt
      args:
        chdir: /app 

    - name: copy payment.service
      ansible.builtin.copy: 
        src: payment.service
        dest: /etc/systemd/system

    - name: daemon reload
      ansible.builtin.systemd_service: 
        daemon_reload: true

    - name: Enable and start payment service
      ansible.builtin.service: 
        name: payment
        enabled: yes 
        state: restarted

        
